# -*- coding: utf-8 -*-
"""fibonacci

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A7P2rW2456FssiVjHz0ucT90xIxL33cO
"""

fibonacci

n = 10
a = 0
b = 1

for i in range(n):

     print(a, end=" ")
     next = a + b
     a = b
     b = next